# Generated by Django 5.2.17 on 2026-10-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=40, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стиралка',
                'verbose_name_plural': 'Стиралки',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('apartment', models.CharField(max_length=20, verbose_name='Квартира')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Жилец',
                'verbose_name_plural': 'Жильцы',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Сейчас'), ('waiting', 'Ожидает'), ('done', 'Завершена'), ('left', 'Вышел')], default='waiting', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Встал в очередь')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Закончил')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='laundry.machine', verbose_name='Стиралка')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='laundry.resident', verbose_name='Жилец')),
            ],
            options={
                'verbose_name': 'Запись очереди',
                'verbose_name_plural': 'Очередь',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['machine', 'status', 'created_at'], name='laundry_que_machine_68bc9c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'waiting'])), fields=('resident',), name='one_open_queue_per_resident'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('machine',), name='one_active_per_machine')],
            },
        ),
    ]
