# Generated by Django 5.2.17 on 2026-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='resident',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='resident',
            name='telegram_link_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='resident',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='unique_resident_email'),
        ),
    ]
